(function(g){var window=this;'use strict';var MOa=function(a,b){return g.Nb(a,b)},NOa=function(a,b){b=b instanceof g.Dc?b:g.Jc(b,/^data:image\//i.test(b));
a.src=g.Ec(b)},OOa=function(a){if(a instanceof g.Th)return a;
if("function"==typeof a.Fg)return a.Fg(!1);if(g.Ma(a)){var b=0,c=new g.Th;c.i=function(){for(;;){if(b>=a.length)throw g.Zh;if(b in a)return a[b++];b++}};
c.next=c.i.bind(c);return c}throw Error("Not implemented");},POa=function(a,b,c){if(g.Ma(a))try{g.Bb(a,b,c)}catch(d){if(d!==g.Zh)throw d;
}else{a=OOa(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(d){if(d!==g.Zh)throw d;}}},C6=function(a){g.ok(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Sa()).toString(36));
return a},D6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.tk(a.l,b,c)},QOa=function(a,b){var c=[];
POa(b,function(d){try{var e=g.hr.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.gr(e)&&c.push(d)},a);
return c},ROa=function(a,b){QOa(a,b).forEach(function(c){g.hr.prototype.remove.call(this,c)},a)},SOa=function(a){if(a.U){if(a.U.locationOverrideToken)return{locationOverrideToken:a.U.locationOverrideToken};
if(null!=a.U.latitudeE7&&null!=a.U.longitudeE7)return{latitudeE7:a.U.latitudeE7,longitudeE7:a.U.longitudeE7}}return null},TOa=function(a,b){g.jb(a,b)||a.push(b)},E6=function(a){var b=0,c;
for(c in a)b++;return b},UOa=function(a){try{return g.A.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},F6=function(a){if(g.A.JSON)try{return g.A.JSON.parse(a)}catch(b){}return UOa(a)},VOa=function(a,b,c,d){var e=new g.ak(null,void 0);
a&&g.bk(e,a);b&&g.ck(e,b);c&&g.dk(e,c);d&&(e.J=d);return e},G6=function(a,b){g.qu[a]=!0;
var c=g.ou();c&&c.publish.apply(c,arguments);g.qu[a]=!1},H6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.ai;this.model=this.brand="";this.year=0;this.chipset=this.osVersion=this.os="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",WOa(this,a.capabilities||""),XOa(this,a.experiments||""),
this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",this.osVersion=a.osVersion||"",this.chipset=a.chipset||"")},WOa=function(a,b){a.capabilities.clear();
g.Po(b.split(","),g.Qa(MOa,YOa)).forEach(function(c){a.capabilities.add(c)})},XOa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},I6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},J6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},ZOa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},$Oa=function(a){return new I6(a)},aPa=function(a){return Array.isArray(a)?g.Oe(a,$Oa):[]},K6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},L6=function(a){return Array.isArray(a)?"["+g.Oe(a,K6).join(",")+"]":"null"},M6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},bPa=function(a){return g.Oe(a,function(b){return{key:b.id,
name:b.name}})},N6=function(a,b){return g.fb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},O6=function(a,b){return g.fb(a,function(c){return J6(c,b)})},cPa=function(){var a=(0,g.gy)();
a&&ROa(a,a.i.Fg(!0))},P6=function(){var a=g.jy("yt-remote-connected-devices")||[];
g.yb(a);return a},dPa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Oe(a,function(d,e){return 0==e?d:d.substring(c.length)})},ePa=function(a){g.iy("yt-remote-connected-devices",a,86400)},R6=function(){if(Q6)return Q6;
var a=g.jy("yt-remote-device-id");a||(a=M6(),g.iy("yt-remote-device-id",a,31536E3));for(var b=P6(),c=1,d=a;g.jb(b,d);)c++,d=a+"#"+c;return Q6=d},S6=function(){var a=P6(),b=R6();
g.jb(a,b);g.Vy()&&g.Ab(a,b);a=dPa(a);if(0==a.length)try{g.Zs("remote_sid")}catch(c){}else try{g.Xs("remote_sid",a.join(","),-1)}catch(c){}},fPa=function(){return g.jy("yt-remote-session-browser-channel")},gPa=function(){return g.jy("yt-remote-local-screens")||[]},hPa=function(){g.iy("yt-remote-lounge-token-expiration",!0,86400)},iPa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Oe(gPa(),function(d){return d.loungeToken}),c=g.Oe(a,function(d){return d.loungeToken});
g.ym(c,function(d){return!g.jb(b,d)})&&hPa();
g.iy("yt-remote-local-screens",a,31536E3)},jPa=function(a,b){g.iy("yt-remote-session-browser-channel",a);
g.iy("yt-remote-session-screen-id",b);a=P6();b=R6();g.jb(a,b)||a.push(b);ePa(a);S6()},T6=function(a){a||(g.Uy("yt-remote-session-screen-id"),g.Uy("yt-remote-session-video-id"));
S6();a=P6();g.nb(a,R6());ePa(a)},kPa=function(){if(!U6){var a=g.rr();
a&&(U6=new g.br(a))}},lPa=function(){kPa();
return U6?!!U6.get("yt-remote-use-staging-server"):!1},V6=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},mPa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},nPa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},W6=function(a){a.length?oPa(a.shift(),function(){W6(a)}):X6()},pPa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},oPa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.Aj(d,g.xl(a));(document.head||document.documentElement).appendChild(d)},qPa=function(){var a=V6(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},X6=function(){var a=nPa();
a&&a(!1,"No cast extension found")},Y6=function(){if(rPa){var a=2,b=nPa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;oPa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",X6,c)}},sPa=function(){Y6();
var a=qPa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");W6(a)},uPa=function(){Y6();
var a=qPa();a.push.apply(a,g.ma(tPa.map(pPa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");W6(a)},Z6=function(a,b,c){g.E.call(this);
this.G=null!=c?(0,g.C)(a,c):a;this.Of=b;this.C=(0,g.C)(this.lN,this);this.i=!1;this.l=0;this.u=this.Gb=null;this.B=[]},$6=function(a,b,c){g.E.call(this);
this.B=null!=c?a.bind(c):a;this.Of=b;this.u=null;this.i=!1;this.l=0;this.Gb=null},a7=function(a){a.Gb=g.ih(function(){a.Gb=null;
a.i&&!a.l&&(a.i=!1,a7(a))},a.Of);
var b=a.u;a.u=null;a.B.apply(null,b)},b7=function(){},c7=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.A.setTimeout(function(){a()},b)},e7=function(a){d7.dispatchEvent(new vPa(d7,a))},vPa=function(a,b){g.gf.call(this,"statevent",a);
this.stat=b},f7=function(a,b,c,d){this.i=a;
this.l=b;this.K=c;this.J=d||1;this.C=45E3;this.B=new g.uk(this);this.u=new g.hh;this.u.setInterval(250)},xPa=function(a,b,c){a.yr=1;
a.Zl=C6(b.clone());a.lp=c;a.G=!0;wPa(a,null)},g7=function(a,b,c,d,e){a.yr=1;
a.Zl=C6(b.clone());a.lp=null;a.G=c;e&&(a.kK=!1);wPa(a,d)},wPa=function(a,b){a.dr=Date.now();
h7(a);a.hn=a.Zl.clone();D6(a.hn,"t",a.J);a.Zu=0;a.Qe=a.i.IA(a.i.Hu()?b:null);0<a.Dz&&(a.Qx=new $6((0,g.C)(a.hL,a,a.Qe),a.Dz));a.B.Qa(a.Qe,"readystatechange",a.mN);b=a.Kn?g.Ub(a.Kn):{};a.lp?(a.Iy="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.Qe.send(a.hn,a.Iy,a.lp,b)):(a.Iy="GET",a.kK&&!g.hg&&(b.Connection="close"),a.Qe.send(a.hn,a.Iy,null,b));a.i.aj(1)},APa=function(a,b,c){for(var d=!0;!a.Wn&&a.Zu<c.length;){var e=yPa(a,c);
if(e==i7){4==b&&(a.Vl=4,e7(15),d=!1);break}else if(e==zPa){a.Vl=4;e7(16);d=!1;break}else j7(a,e)}4==b&&0==c.length&&(a.Vl=1,e7(17),d=!1);a.lj=a.lj&&d;d||(k7(a),l7(a))},yPa=function(a,b){var c=a.Zu,d=b.indexOf("\n",c);
if(-1==d)return i7;c=Number(b.substring(c,d));if(isNaN(c))return zPa;d+=1;if(d+c>b.length)return i7;b=b.substr(d,c);a.Zu=d+c;return b},CPa=function(a,b){a.dr=Date.now();
h7(a);var c=b?window.location.hostname:"";a.hn=a.Zl.clone();g.ok(a.hn,"DOMAIN",c);g.ok(a.hn,"t",a.J);try{a.qj=new ActiveXObject("htmlfile")}catch(m){k7(a);a.Vl=7;e7(22);l7(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in m7)f=m7[f];else if(f in BPa)f=m7[f]=BPa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
m7[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.dd(g.fc("b/12014412"),d+"</body></html>");a.qj.open();a.qj.write(g.$c(c));a.qj.close();a.qj.parentWindow.m=(0,g.C)(a.zT,a);a.qj.parentWindow.d=(0,g.C)(a.CJ,a,!0);a.qj.parentWindow.rpcClose=(0,g.C)(a.CJ,a,!1);c=a.qj.createElement("DIV");a.qj.parentWindow.document.body.appendChild(c);d=g.Ic(a.hn.toString());d=g.pd(g.Ec(d));d=g.dd(g.fc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.id(c,d);a.i.aj(1)},h7=function(a){a.XD=Date.now()+
a.C;
DPa(a,a.C)},DPa=function(a,b){if(null!=a.Dr)throw Error("WatchDog timer not null");
a.Dr=c7((0,g.C)(a.HT,a),b)},n7=function(a){a.Dr&&(g.A.clearTimeout(a.Dr),a.Dr=null)},l7=function(a){a.i.We()||a.Wn||a.i.Av(a)},k7=function(a){n7(a);
g.df(a.Qx);a.Qx=null;a.u.stop();g.wk(a.B);if(a.Qe){var b=a.Qe;a.Qe=null;b.abort();b.dispose()}a.qj&&(a.qj=null)},j7=function(a,b){try{a.i.vJ(a,b),a.i.aj(4)}catch(c){}},FPa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;EPa(a,b,function(h){h?c(!0):g.A.setTimeout(function(){FPa(a,b,c,d,f)},f)})}},EPa=function(a,b,c){var d=new Image;
d.onload=function(){try{o7(d),c(!0)}catch(e){}};
d.onerror=function(){try{o7(d),c(!1)}catch(e){}};
d.onabort=function(){try{o7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{o7(d),c(!1)}catch(e){}};
g.A.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
NOa(d,a)},o7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},GPa=function(a){this.i=a;
this.l=new b7},HPa=function(a){var b=p7(a.i,a.ys,"/mail/images/cleardot.gif");
C6(b);FPa(b.toString(),5E3,(0,g.C)(a.iO,a),3,2E3);a.aj(1)},r7=function(a){var b=a.i.K;
if(null!=b)e7(5),b?(e7(11),q7(a.i,a,!1)):(e7(12),q7(a.i,a,!0));else if(a.Yg=new f7(a,void 0,void 0,void 0),a.Yg.Kn=a.Ez,b=a.i,b=p7(b,b.Hu()?a.Yr:null,a.Fz),e7(5),!g.be||g.Wd(10))D6(b,"TYPE","xmlhttp"),g7(a.Yg,b,!1,a.Yr,!1);else{D6(b,"TYPE","html");var c=a.Yg;a=!!a.Yr;c.yr=3;c.Zl=C6(b.clone());CPa(c,a)}},s7=function(a,b,c){this.Oa=1;
this.i=[];this.u=[];this.B=new b7;this.J=a||null;this.K=null!=b?b:null;this.C=c||!1},IPa=function(a,b){this.i=a;
this.map=b;this.context=null},JPa=function(a,b,c,d){g.gf.call(this,"timingevent",a);
this.size=b;this.Bu=d},KPa=function(a){g.gf.call(this,"serverreachability",a)},NPa=function(a){LPa(a);
if(3==a.Oa){var b=a.Rt++,c=a.cw.clone();g.ok(c,"SID",a.l);g.ok(c,"RID",b);g.ok(c,"TYPE","terminate");t7(a,c);b=new f7(a,a.l,b,void 0);b.yr=2;b.Zl=C6(c.clone());NOa(new Image,b.Zl.toString());b.dr=Date.now();h7(b)}MPa(a)},OPa=function(a){a.IO(1,0);
a.cw=p7(a,null,a.Gz);u7(a)},LPa=function(a){a.gm&&(a.gm.abort(),a.gm=null);
a.oe&&(a.oe.cancel(),a.oe=null);a.Tk&&(g.A.clearTimeout(a.Tk),a.Tk=null);v7(a);a.Mg&&(a.Mg.cancel(),a.Mg=null);a.qm&&(g.A.clearTimeout(a.qm),a.qm=null)},PPa=function(a,b){if(0==a.Oa)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new IPa(a.rQ++,b));2!=a.Oa&&3!=a.Oa||u7(a)},QPa=function(a){var b=0;
a.oe&&b++;a.Mg&&b++;return b},u7=function(a){a.Mg||a.qm||(a.qm=c7((0,g.C)(a.AJ,a),0),a.xq=0)},SPa=function(a,b){if(1==a.Oa){if(!b){a.Rt=Math.floor(1E5*Math.random());
b=a.Rt++;var c=new f7(a,"",b,void 0);c.Kn=a.Ej;var d=w7(a),e=a.cw.clone();g.ok(e,"RID",b);g.ok(e,"CVER","1");t7(a,e);xPa(c,e,d);a.Mg=c;a.Oa=2}}else 3==a.Oa&&(b?RPa(a,b):0==a.i.length||a.Mg||RPa(a))},RPa=function(a,b){if(b)if(6<a.Xn){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.Rt-1;b=w7(a)}else c=b.K,b=b.lp;else c=a.Rt++,b=w7(a);var d=a.cw.clone();g.ok(d,"SID",a.l);g.ok(d,"RID",c);g.ok(d,"AID",a.Mq);t7(a,d);c=new f7(a,a.l,c,a.xq+1);c.Kn=a.Ej;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Mg=c;xPa(c,d,b)},t7=function(a,b){a.Kf&&(a=a.Kf.bH())&&g.Db(a,function(c,d){g.ok(b,d,c)})},w7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Xn&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Op:e.Op},f++){e.Op=a.i[f].i;var h=a.i[f].map;e.Op=6>=a.Xn?f:e.Op-d;try{g.Db(h,function(l){return function(m,n){c.push("req"+l.Op+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Op+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},TPa=function(a){a.oe||a.Tk||(a.G=1,a.Tk=c7((0,g.C)(a.zJ,a),0),a.gq=0)},x7=function(a){if(a.oe||a.Tk||3<=a.gq)return!1;
a.G++;a.Tk=c7((0,g.C)(a.zJ,a),UPa(a,a.gq));a.gq++;return!0},q7=function(a,b,c){a.Gy=c;
a.Fj=b.Dk;a.C||OPa(a)},v7=function(a){null!=a.uo&&(g.A.clearTimeout(a.uo),a.uo=null)},UPa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},y7=function(a,b){if(2==b||9==b){var c=null;
a.Kf&&(c=null);var d=(0,g.C)(a.HU,a);c||(c=new g.ak("//www.google.com/images/cleardot.gif"),C6(c));EPa(c.toString(),1E4,d)}else e7(2);VPa(a,b)},VPa=function(a,b){a.Oa=0;
a.Kf&&a.Kf.pG(b);MPa(a);LPa(a)},MPa=function(a){a.Oa=0;
a.Fj=-1;if(a.Kf)if(0==a.u.length&&0==a.i.length)a.Kf.vA();else{g.qb(a.u);var b=g.qb(a.i);a.u.length=0;a.i.length=0;a.Kf.vA(b)}},p7=function(a,b,c){var d=g.pk(c);
if(""!=d.i)b&&g.ck(d,b+"."+d.i),g.dk(d,d.u);else{var e=window.location;d=VOa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Ps&&g.Db(a.Ps,function(f,h){g.ok(d,h,f)});
g.ok(d,"VER",a.Xn);t7(a,d);return d},WPa=function(){},XPa=function(){this.i=[];
this.l=[]},YPa=function(a,b){this.action=a;
this.params=b||{}},z7=function(a,b){g.E.call(this);
this.i=new g.J(this.rT,0,this);g.F(this,this.i);this.Of=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.C)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.C)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},A7=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.ma=a;this.G=b;this.u=new g.ar;this.l=new z7(this.mU,this);this.i=null;this.Y=!1;this.C=null;this.U="";this.K=this.B=0;this.J=[];this.va=c;this.X=d;this.xa=e},ZPa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.Gy,sessionId:a.i.l,arrayId:a.i.Mq}},$Pa=function(a,b){a.K=b||0;
a.l.stop();B7(a);a.i&&(3==a.i.getState()&&SPa(a.i),NPa(a.i));a.K=0},C7=function(a){return!!a.i&&3==a.i.getState()},B7=function(a){if(a.i){var b=a.X(),c=a.i.Ej||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Ej=c}},D7=function(a){this.port=this.domain="";
this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.gi(4,a))||"";b&&(this.port=":"+b);this.domain=g.hi(a)||"";a=g.Tc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Bc(a,"10.0")&&(this.l=!1))},E7=function(a,b){var c=a.i;
a.l&&(c="https://"+a.domain+a.port+a.i);return g.si(c+b,{})},F7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.B,d,!0),onError:g.Qa(a.u,e),onTimeout:g.Qa(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.qs(b,a)},dQa=function(){var a=aQa;
bQa();G7.push(a);cQa()},H7=function(a,b){bQa();
var c=eQa(a,String(b));0==G7.length?fQa(c):(cQa(),g.Bb(G7,function(d){d(c)}))},bQa=function(){G7||(G7=g.Ia("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",G7,void 0))},fQa=function(a){var b=(I7+1)%50;
I7=b;J7[b]=a;K7||(K7=49==b)},cQa=function(){var a=G7;
if(J7[0]){var b=K7?I7:-1;do{b=(b+1)%50;var c=J7[b];g.Bb(a,function(d){d(c)})}while(b!=I7);
J7=Array(50);I7=-1;K7=!1}},eQa=function(a,b){var c=(Date.now()-gQa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},L7=function(a){g.Q.call(this);
this.G=a;this.screens=[]},hQa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},iQa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Po(a.screens,function(f){return!!N6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=hQa(a,b[d])||c;return c},jQa=function(a,b){var c=a.screens.length;
a.screens=g.Po(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},M7=function(a,b,c,d,e){g.Q.call(this);
this.u=a;this.J=b;this.B=c;this.G=d;this.C=e;this.l=0;this.i=null;this.Gb=NaN},O7=function(a){L7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;N7(this);this.info("Initializing with "+L6(this.screens))},kQa=function(a){if(a.screens.length){var b=g.Oe(a.screens,function(d){return d.id}),c=E7(a.l,"/pairing/get_lounge_token_batch");
F7(a.l,c,{screen_ids:b.join(",")},(0,g.C)(a.hP,a),(0,g.C)(a.gP,a))}},N7=function(a){if(g.Kr("deprecate_pair_servlet_enabled"))return iQa(a,[]);
var b=aPa(gPa());b=g.Po(b,function(c){return!c.uuid});
return iQa(a,b)},P7=function(a,b){iPa(g.Oe(a.screens,ZOa));
b&&hPa()},R7=function(a,b){g.Q.call(this);
this.G=b;b=(b=g.jy("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.G(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.jb(b,h)}this.i=c;this.C=a;this.u=this.B=NaN;this.l=null;Q7("Initialized with "+g.Mh(this.i))},S7=function(a,b,c){var d=E7(a.C,"/pairing/get_screen_availability");
F7(a.C,d,{lounge_token:b.token},(0,g.C)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.C)(function(){c(!1)},a))},T7=function(a,b){a:if(E6(b)!=E6(a.i))var c=!1;
else{c=g.Lb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(Q7("Updated online screens: "+g.Mh(a.i)),a.i=b,a.W("screenChange"));lQa(a)},U7=function(a){isNaN(a.u)||g.ls(a.u);
a.u=g.js((0,g.C)(a.VC,a),0<a.B&&a.B<g.Sa()?2E4:1E4)},Q7=function(a){H7("OnlineScreenService",a)},mQa=function(a){var b={};
g.Bb(a.G(),function(c){c.token?b[c.token]=c.id:this.Sd("Requesting availability of screen w/o lounge token.")});
return b},lQa=function(a){a=g.Lb(g.Eb(a.i,function(b){return b}));
g.yb(a);a.length?g.iy("yt-remote-online-screen-ids",a.join(","),60):g.Uy("yt-remote-online-screen-ids")},V7=function(a,b){b=void 0===b?!1:b;
L7.call(this,"ScreenService");this.B=a;this.J=b;this.i=this.l=null;this.u=[];this.C={};nQa(this)},pQa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.oh(),l=c?O6(h,c):null;c&&(a.J||l)||(l=O6(h,b));if(l){l.uuid=b;var m=W7(a,l);S7(a.i,m,function(n){e(n?m:null)})}else c?oQa(a,c,(0,g.C)(function(n){var p=W7(this,new I6({name:d,
screenId:c,loungeToken:n,dialId:b||""}));S7(this.i,p,function(r){e(r?p:null)})},a),f):e(null)},qQa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},rQa=function(a,b,c){S7(a.i,b,c)},oQa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.qs(E7(a.B,"/pairing/get_lounge_token_batch"),e)},sQa=function(a){a.screens=a.l.oh();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+L6(a.screens))},nQa=function(a){X7(a);
a.l=new O7(a.B);a.l.subscribe("screenChange",(0,g.C)(a.qP,a));sQa(a);a.J||(a.u=aPa(g.jy("yt-remote-automatic-screen-cache")||[]));X7(a);a.info("Initializing automatic screens: "+L6(a.u));a.i=new R7(a.B,(0,g.C)(a.oh,a,!0));a.i.subscribe("screenChange",(0,g.C)(function(){this.W("onlineScreenChange")},a))},W7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=O6(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),a.J||tQa(a));X7(a);a.C[b.uuid]=b.id;g.iy("yt-remote-device-id-map",a.C,31536E3);return b},tQa=function(a){a=g.Po(a.u,function(b){return"shortLived"!=b.idType});
g.iy("yt-remote-automatic-screen-cache",g.Oe(a,ZOa))},X7=function(a){a.C=g.jy("yt-remote-device-id-map")||{}},Y7=function(a,b,c){g.Q.call(this);
this.xa=c;this.u=a;this.i=b;this.B=null},Z7=function(a,b){a.B=b;
a.W("sessionScreen",a.B)},uQa=function(a,b){a.B&&(a.B.token=b,W7(a.u,a.B));
a.W("sessionScreen",a.B)},$7=function(a,b){H7(a.xa,b)},a8=function(a,b,c){Y7.call(this,a,b,"CastSession");
var d=this;this.config_=c;this.l=null;this.X=(0,g.C)(this.rN,this);this.va=(0,g.C)(this.KT,this);this.Y=g.js(function(){vQa(d,null)},12E4);
this.J=this.C=this.G=this.K=0;this.ma=!1;this.U="unknown"},b8=function(a,b){g.ls(a.J);
a.J=0;0==b?wQa(a):a.J=g.js(function(){wQa(a)},b)},wQa=function(a){xQa(a,"getLoungeToken");
g.ls(a.C);a.C=g.js(function(){yQa(a,null)},3E4)},xQa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Mh(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ja,(0,g.C)(function(){$7(this,"Failed to send message: "+b+".")},a)):$7(a,"Sending yt message without session: "+g.Mh(c))},c8=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.qH(b,function(c){Z7(a,c)},function(){return a.pg()},5)):a.pg(Error("Waiting for session status timed out."))},AQa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new I6(b);zQa(a,d,function(e){e?(a.ma=!0,W7(a.u,d),Z7(a,d),a.U="unknown",b8(a,c)):(g.Pr(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.pg())},5)},vQa=function(a,b){g.ls(a.Y);
a.Y=0;b?a.config_.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?AQa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.Pr(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),c8(a,b.screenId))):(g.Pr(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+
".")),c8(a,b.screenId)):c8(a,b.screenId):a.pg(Error("Waiting for session status timed out."))},yQa=function(a,b){g.ls(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.U=c,b8(a,3E4)):(uQa(a,b.loungeToken),a.ma=!1,a.U="unknown",b8(a,b.loungeTokenRefreshIntervalMs))},zQa=function(a,b,c,d){g.ls(a.G);
a.G=0;rQa(a.u,b,function(e){e||0>d?c(e):a.G=g.js(function(){zQa(a,b,c,d-1)},300)})},BQa=function(a){g.ls(a.K);
a.K=0;g.ls(a.G);a.G=0;g.ls(a.Y);a.Y=0;g.ls(a.C);a.C=0;g.ls(a.J);a.J=0},d8=function(a,b,c,d){Y7.call(this,a,b,"DialSession");
this.config_=d;this.l=this.K=null;this.va="";this.Da=c;this.Ea=null;this.Y=g.Ja;this.U=NaN;this.Aa=(0,g.C)(this.sN,this);this.C=g.Ja;this.J=this.G=0;this.X=!1;this.ma="unknown"},e8=function(a){var b;
return!!(a.config_.enableDialLoungeToken&&(null==(b=a.l)?0:b.getDialAppInfo))},CQa=function(a){a.C=a.u.VE(a.va,a.i.label,a.i.friendlyName,e8(a),function(b,c){a.C=g.Ja;
a.X=!0;Z7(a,b);"shortLived"==b.idType&&0<c&&f8(a,c)},function(b){a.C=g.Ja;
a.pg(b)})},DQa=function(a){var b={};
b.pairingCode=a.va;b.theme=a.Da;lPa()&&(b.env_useStageMdx=1);return g.qi(b)},g8=function(a){return new Promise(function(b){a.va=M6();
if(a.Ea){var c=new chrome.cast.DialLaunchResponse(!0,DQa(a));b(c);CQa(a)}else a.Y=function(){g.ls(a.U);a.Y=function(){};
a.U=NaN;var d=new chrome.cast.DialLaunchResponse(!0,DQa(a));b(d);CQa(a)},a.U=g.js(function(){a.Y()},100)})},FQa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new I6(b);return(new Promise(function(e){EQa(a,d,function(f){f?(a.X=!0,W7(a.u,d),Z7(a,d),f8(a,c)):g.Pr(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):g8(a)})},GQa=function(a,b){var c=a.K.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){pQa(a.u,c,b,d,function(f){f&&f.token&&Z7(a,f);e(f)},function(f){$7(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):g8(a)})},EQa=function(a,b,c,d){g.ls(a.G);
a.G=0;rQa(a.u,b,function(e){e||0>d?c(e):a.G=g.js(function(){EQa(a,b,c,d-1)},300)})},f8=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
e8(a)&&(g.ls(a.J),a.J=0,0==b?HQa(a):a.J=g.js(function(){HQa(a)},b))},HQa=function(a){e8(a)&&a.l.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.ma=c,f8(a,3E4)):(a.X=!1,a.ma="unknown",uQa(a,b.loungeToken),f8(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.ma="noLoungeTokenResponse";f8(a,3E4)})},IQa=function(a){g.ls(a.G);
a.G=0;g.ls(a.J);a.J=0;a.C();a.C=function(){};
g.ls(a.U)},h8=function(a,b){Y7.call(this,a,b,"ManualSession");
this.l=g.js((0,g.C)(this.Nq,this,null),150)},i8=function(a,b){g.Q.call(this);
this.config_=b;this.l=a;this.J=b.appId||"233637DE";this.B=b.theme||"cl";this.K=b.disableCastApi||!1;this.U=b.forceMirroring||!1;this.i=null;this.G=!1;this.u=[];this.C=(0,g.C)(this.CS,this)},JQa=function(a,b){return b?g.fb(a.u,function(c){return J6(b,c.label)},a):null},j8=function(a){H7("Controller",a)},aQa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},k8=function(a){return a.G||!!a.u.length||!!a.i},l8=function(a,b,c){b!=a.i&&(g.df(a.i),(a.i=b)?(c?a.W("yt-remote-cast2-receiver-resumed",
b.i):a.W("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.C)(a.yJ,a,b)),b.getScreen()?a.W("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Nq(null)):a.W("yt-remote-cast2-session-change",null))},KQa=function(a){var b=a.l.UE(),c=a.i&&a.i.i;
a=g.Oe(b,function(d){c&&J6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=JQa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},PQa=function(a,b,c,d){d.disableCastApi?m8("Cannot initialize because disabled by Mdx config."):LQa()?MQa(b,d)&&(n8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?NQa(a,c):(window.__onGCastApiAvailable=function(e,f){e?NQa(a,c):(o8("Failed to load cast API: "+f),p8(!1),n8(!1),g.Uy("yt-remote-cast-available"),g.Uy("yt-remote-cast-receiver"),
OQa(),c(!1))},d.loadCastApiSetupScript?g.Wy("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=V6()&&sPa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?X6():89<=V6()?uPa():(Y6(),W6(tPa.map(pPa))))):m8("Cannot initialize because not running Chrome")},OQa=function(){m8("dispose");
var a=q8();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);QQa(!1);g.uu(r8);r8.length=0},s8=function(){return!!g.jy("yt-remote-cast-installed")},RQa=function(){var a=g.jy("yt-remote-cast-receiver");
return a?a.friendlyName:null},SQa=function(){m8("clearCurrentReceiver");
g.Uy("yt-remote-cast-receiver")},TQa=function(){return s8()?q8()?q8().getCastSession():(o8("getCastSelector: Cast is not initialized."),null):(o8("getCastSelector: Cast API is not installed!"),null)},u8=function(){s8()?q8()?t8()?(m8("Requesting cast selector."),q8().requestSession()):(m8("Wait for cast API to be ready to request the session."),r8.push(g.tu("yt-remote-cast2-api-ready",u8))):o8("requestCastSelector: Cast is not initialized."):o8("requestCastSelector: Cast API is not installed!")},v8=
function(a,b){t8()?q8().setConnectedScreenStatus(a,b):o8("setConnectedScreenStatus called before ready.")},LQa=function(){var a=0<=g.Tc.search(/ (CrMo|Chrome|CriOS)\//);
return g.$i||a},UQa=function(a,b){q8().init(a,b)},MQa=function(a,b){var c=!1;
q8()||(a=new i8(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.iy("yt-remote-cast-available",d);G6("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){m8("onReceiverSelected: "+d.friendlyName);
g.iy("yt-remote-cast-receiver",d);G6("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){m8("onReceiverResumed: "+d.friendlyName);
g.iy("yt-remote-cast-receiver",d);G6("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){m8("onSessionChange: "+K6(d));
d||g.Uy("yt-remote-cast-receiver");G6("yt-remote-cast2-session-change",d)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
m8("cloudview.createSingleton_: "+c);return c},q8=function(){return g.Ia("yt.mdx.remote.cloudview.instance_")},NQa=function(a,b){p8(!0);
n8(!1);UQa(a,function(c){c?(QQa(!0),g.vu("yt-remote-cast2-api-ready")):(o8("Failed to initialize cast API."),p8(!1),g.Uy("yt-remote-cast-available"),g.Uy("yt-remote-cast-receiver"),OQa());b(c)})},m8=function(a){H7("cloudview",a)},o8=function(a){H7("cloudview",a)},p8=function(a){m8("setCastInstalled_ "+a);
g.iy("yt-remote-cast-installed",a)},t8=function(){return!!g.Ia("yt.mdx.remote.cloudview.apiReady_")},QQa=function(a){m8("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},n8=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},w8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.G=this.J=0;this.trackData=null;this.hasNext=this.Uj=!1;this.K=this.C=this.i=this.B=0;this.u=NaN;this.l=!1;this.reset(a)},x8=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Uj=!1;a.hasNext=!1;a.J=0;a.G=g.Sa();a.B=0;a.i=0;a.C=0;a.K=0;a.u=NaN;a.l=!1},y8=function(a){return a.tc()?(g.Sa()-a.G)/1E3:0},z8=function(a,b){a.J=b;
a.G=g.Sa()},A8=function(a){switch(a.playerState){case 1:case 1081:return(g.Sa()-a.G)/1E3+a.J;
case -1E3:return 0}return a.J},B8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&x8(a)},C8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Vb(a.trackData);b.hasPrevious=a.Uj;b.hasNext=a.hasNext;b.playerTime=a.J;b.playerTimeAt=a.G;b.seekableStart=a.B;b.seekableEnd=a.i;b.duration=a.C;b.loadedTime=a.K;b.liveIngestionTime=a.u;return b},E8=function(a,b){g.Q.call(this);
this.Oa=0;this.u=a;this.C=[];this.B=new XPa;this.l=this.i=null;this.K=(0,g.C)(this.aR,this);this.G=(0,g.C)(this.Vt,this);this.J=(0,g.C)(this.ZQ,this);this.U=(0,g.C)(this.hR,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.iD,this),VQa(this))):c=3;0!=c&&(b?this.iD(c):g.js((0,g.C)(function(){this.iD(c)},this),0));
(a=TQa())&&D8(this,a);this.subscribe("yt-remote-cast2-session-change",this.U)},F8=function(a){return new w8(a.u.getPlayerContextData())},VQa=function(a){g.Bb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Qa(this.zS,b),this))},a)},WQa=function(a){g.Bb(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},G8=function(a){return 1==a.getState()},H8=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},J8=function(a,b,c){var d=F8(a);
z8(d,c);-1E3!=d.playerState&&(d.playerState=b);I8(a,d)},K8=function(a,b,c){a.u.sendMessage(b,c)},I8=function(a,b){WQa(a);
a.u.setPlayerContextData(C8(b));VQa(a)},D8=function(a,b){a.l&&(a.l.removeUpdateListener(a.K),a.l.removeMediaListener(a.G),a.Vt(null));
a.l=b;a.l&&(H7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.K),a.l.addMediaListener(a.G),a.l.media.length&&a.Vt(a.l.media[0]))},XQa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=F8(a);b.contentId!=d.videoId&&H7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;z8(d,a.i.getEstimatedTime());I8(a,d)}else H7("CP","No cast media video. Ignoring state update.")},L8=function(a,b,c){return(0,g.C)(function(d){this.Sd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Sd("Retrying "+b+" using MDx browser channel."),K8(this,b,c))},a)},M8=function(a,b,c){g.Q.call(this);
this.C=NaN;this.ma=!1;this.K=this.J=this.Y=this.X=NaN;this.U=[];this.B=this.G=this.u=this.dc=this.i=null;this.xa=a;this.U.push(g.Lt(window,"beforeunload",(0,g.C)(this.cP,this)));this.l=[];this.dc=new w8;this.Aa=b.id;this.va=b.idType;this.i=YQa(this,c);this.i.subscribe("handlerOpened",this.eR,this);this.i.subscribe("handlerClosed",this.bR,this);this.i.subscribe("handlerError",this.cR,this);this.i.subscribe("handlerMessage",this.dR,this);this.i.ey(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.dc.videoId;g.Vy()&&g.iy("yt-remote-session-video-id",d)},this)},N8=function(a){H7("conn",a)},YQa=function(a,b){return new A7(E7(a.xa,"/bc"),b,!1,function(){return a.ZE()},"shortLived"==a.va)},O8=function(a,b){a.W("proxyStateChange",b)},ZQa=function(a){a.C=g.js((0,g.C)(function(){N8("Connecting timeout");
this.rq(1)},a),2E4)},P8=function(a){g.ls(a.C);
a.C=NaN},Q8=function(a){g.ls(a.X);
a.X=NaN},$Qa=function(a){R8(a);
a.Y=g.js((0,g.C)(function(){S8(this,"getNowPlaying")},a),2E4)},R8=function(a){g.ls(a.Y);
a.Y=NaN},bRa=function(a,b){b&&(P8(a),Q8(a));
var c=C7(a.i)&&isNaN(a.C);b==c?b&&(O8(a,1),S8(a,"getSubtitlesTrack")):b?(a.oH()&&a.dc.reset(),O8(a,1),S8(a,"getNowPlaying"),aRa(a)):a.rq(1)},cRa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.dc.videoId&&(g.Qb(b.params)?a.dc.trackData=null:a.dc.trackData=b.params,a.W("remotePlayerChange"))},dRa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.dc.listId=b.params.listId||a.dc.listId;B8(a.dc,c,d);a.W("remoteQueueChange")},fRa=function(a,b){b.params=b.params||{};
dRa(a,b);eRa(a,b);a.W("autoplayDismissed")},eRa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
z8(a.dc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.dc.playerState&&(c=-1E3);a.dc.playerState=c;c=Number(b.params.loadedTime);a.dc.K=isNaN(c)?0:c;c=Number(b.params.duration);a.dc.C=isNaN(c)?0:c;c=a.dc;var d=Number(b.params.liveIngestionTime);c.u=d;c.l=isNaN(d)?!1:!0;c=a.dc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.dc.playerState?$Qa(a):R8(a);a.W("remotePlayerChange")},gRa=function(a,b){if(-1E3!=a.dc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.dc.playerState=c;b=parseInt(b.params.currentTime,10);z8(a.dc,isNaN(b)?0:b);a.W("remotePlayerChange")}},hRa=function(a,b){var c="true"==b.params.muted;
a.dc.volume=parseInt(b.params.volume,10);a.dc.muted=c;a.W("remotePlayerChange")},iRa=function(a,b){a.G=b.params.videoId;
a.W("nowAutoplaying",parseInt(b.params.timeout,10))},jRa=function(a,b){var c="true"==b.params.hasNext;
a.dc.Uj="true"==b.params.hasPrevious;a.dc.hasNext=c;a.W("previousNextChange")},aRa=function(a){g.ls(a.K);
a.K=g.js((0,g.C)(a.rq,a,1),864E5)},S8=function(a,b,c){c?N8("Sending: action="+b+", params="+g.Mh(c)):N8("Sending: action="+b);
a.i.sendMessage(b,c)},T8=function(a){L7.call(this,"ScreenServiceProxy");
this.ye=a;this.i=[];this.i.push(this.ye.$_s("screenChange",(0,g.C)(this.wN,this)));this.i.push(this.ye.$_s("onlineScreenChange",(0,g.C)(this.gS,this)))},nRa=function(a,b){kPa();
if(!U6||!U6.get("yt-remote-disable-remote-module-for-dev")){b=g.O("MDX_CONFIG")||b;cPa();S6();U8||(U8=new D7(b?b.loungeApiHost:void 0),lPa()&&(U8.i="/api/loungedev"));V8||(V8=g.Ia("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",V8,void 0));kRa();var c=W8();if(!c){var d=new V7(U8,b?b.disableAutomaticScreenCache||!1:!1);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=W8();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken,forceMirroring:b.forceMirroring});PQa(a,d,function(f){f?X8()&&v8(X8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){G6("yt-remote-receiver-availability-change")})},e)}b&&!g.Ia("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),Y8("Initializing: "+g.Mh(b)),Z8.push(g.tu("yt-remote-cast2-availability-change",function(){G6("yt-remote-receiver-availability-change")})),
Z8.push(g.tu("yt-remote-cast2-receiver-selected",function(){$8(null);
G6("yt-remote-auto-connect","cast-selector-receiver")})),Z8.push(g.tu("yt-remote-cast2-receiver-resumed",function(){G6("yt-remote-receiver-resumed","cast-selector-receiver")})),Z8.push(g.tu("yt-remote-cast2-session-change",lRa)),Z8.push(g.tu("yt-remote-connection-change",function(f){f?v8(X8(),"YouTube TV"):a9()||(v8(null,null),SQa())})),a=b9(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.Kr("desktop_enable_autoplay")&&e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=
b.theme)&&(a.theme=b),Y8(" -- with channel params: "+g.Mh(a)),a?(g.iy("yt-remote-session-app",a.app),g.iy("yt-remote-session-name",a.name)):(g.Uy("yt-remote-session-app"),g.Uy("yt-remote-session-name")),g.Ha("yt.mdx.remote.channelParams_",a,void 0),c.start(),X8()||mRa())}},oRa=function(){var a=W8().ye.$_gos();
var b=c9();b&&d9()&&(N6(a,b)||a.push(b));return bPa(a)},e9=function(){var a=pRa();
!a&&s8()&&RQa()&&(a={key:"cast-selector-receiver",name:RQa()});return a},pRa=function(){var a=oRa(),b=c9();
b||(b=a9());return g.fb(a,function(c){return b&&J6(b,c.key)?!0:!1})},c9=function(){var a=X8();
if(!a)return null;var b=W8().oh();return O6(b,a)},lRa=function(a){Y8("remote.onCastSessionChange_: "+K6(a));
if(a){var b=c9();if(b&&b.id==a.id){if(v8(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))f9&&(f9.token=a),(b=d9())&&b.ey(a)}else b&&g9(),h9(a,1)}else d9()&&g9()},g9=function(){t8()?q8().stopSession():o8("stopSession called before API ready.");
var a=d9();a&&(a.disconnect(1),i9(null))},j9=function(){var a=d9();
return!!a&&3!=a.getProxyState()},Y8=function(a){H7("remote",a)},W8=function(){if(!k9){var a=g.Ia("yt.mdx.remote.screenService_");
k9=a?new T8(a):null}return k9},X8=function(){return g.Ia("yt.mdx.remote.currentScreenId_")},qRa=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},rRa=function(){return g.Ia("yt.mdx.remote.connectData_")},$8=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},d9=function(){return g.Ia("yt.mdx.remote.connection_")},i9=function(a){var b=d9();
$8(null);a||qRa("");g.Ha("yt.mdx.remote.connection_",a,void 0);V8&&(g.Bb(V8,function(c){c(a)}),V8.length=0);
b&&!a?G6("yt-remote-connection-change",!1):!b&&a&&G6("yt-remote-connection-change",!0)},a9=function(){var a=g.Vy();
if(!a)return null;var b=W8();if(!b)return null;b=b.oh();return O6(b,a)},h9=function(a,b){X8();
c9()&&c9();l9?f9=a:(qRa(a.id),a=new M8(U8,a,b9()),a.connect(b,rRa()),a.subscribe("beforeDisconnect",function(c){G6("yt-remote-before-disconnect",c)}),a.subscribe("beforeDispose",function(){d9()&&(d9(),i9(null))}),a.subscribe("browserChannelAuthError",function(){var c=c9();
c&&"shortLived"==c.idType&&(t8()?q8().handleBrowserChannelAuthError():o8("refreshLoungeToken called before API ready."))}),i9(a))},mRa=function(){var a=a9();
a?(Y8("Resume connection to: "+K6(a)),h9(a,0)):(T6(),SQa(),Y8("Skipping connecting because no session screen found."))},kRa=function(){var a=b9();
if(g.Qb(a)){a=R6();var b=g.jy("yt-remote-session-name")||"",c=g.jy("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},b9=function(){return g.Ia("yt.mdx.remote.channelParams_")||{}},m9=function(a,b,c){g.E.call(this);
var d=this;this.l=a;this.I=b;this.Pb=c;this.events=new g.pN(this);this.Y=this.events.N(this.I,"onVolumeChange",function(e){sRa(d,e)});
this.C=!1;this.suggestion=null;this.G=new g.zK(64);this.i=new g.J(this.uK,500,this);this.u=new g.J(this.vK,1E3,this);this.K=new Z6(this.ZU,0,this);this.B={};this.U=new g.J(this.bL,1E3,this);this.J=new $6(this.seekTo,1E3,this);this.X=g.Ja;g.F(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.QR);this.events.N(b,"captionschanged",this.XQ);this.events.N(b,"captionssettingschanged",this.BK);this.events.N(b,"videoplayerreset",this.Hx);this.events.N(b,"mdxautoplaycancel",function(){d.Pb.IG()});
a=this.Pb;a.Ha();a.subscribe("proxyStateChange",this.uJ,this);a.subscribe("remotePlayerChange",this.au,this);a.subscribe("remoteQueueChange",this.Hx,this);a.subscribe("previousNextChange",this.rJ,this);a.subscribe("nowAutoplaying",this.lJ,this);a.subscribe("autoplayDismissed",this.LI,this);g.F(this,this.i);g.F(this,this.u);g.F(this,this.K);g.F(this,this.U);g.F(this,this.J);this.BK();this.Hx();this.au()},sRa=function(a,b){if(n9(a)){a.Pb.unsubscribe("remotePlayerChange",a.au,a);
var c=Math.round(b.volume);b=!!b.muted;var d=F8(a.Pb);if(c!==d.volume||b!==d.muted)a.Pb.setVolume(c,b),a.U.start();a.Pb.subscribe("remotePlayerChange",a.au,a)}},tRa=function(a){a.Rb(0);
a.i.stop();a.Lb(new g.zK(64))},o9=function(a,b){if(n9(a)&&!a.C){var c=null;
b&&(c={style:a.I.getSubtitlesUserSettings()},g.Xb(c,b));a.Pb.YE(a.I.getVideoData(1).videoId,c);a.B=F8(a.Pb).trackData}},p9=function(a,b){var c=a.I.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.I.getVideoData(1);a.Pb.playVideo(c.videoId,b,d,e,c.playerParams,c.Ga,SOa(c));a.Lb(new g.zK(1))},uRa=function(a,b){if(b){var c=a.I.getOption("captions","tracklist",{JH:1});
c&&c.length?(a.I.setOption("captions","track",b),a.C=!1):(a.I.loadModule("captions"),a.C=!0)}else a.I.setOption("captions","track",{})},n9=function(a){return F8(a.Pb).videoId===a.I.getVideoData(1).videoId},q9=function(){g.V.call(this,{D:"div",
L:"ytp-mdx-manual-pairing-popup-dialog",V:{role:"dialog"},S:[{D:"div",L:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{D:"div",L:"ytp-mdx-manual-pairing-popup-title",oa:"Connecting to your TV on web using a code will be going away soon"},{D:"div",L:"ytp-mdx-manual-pairing-popup-buttons",S:[{D:"button",Ca:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],oa:"Learn more"},{D:"button",Ca:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],oa:"OK"}]}]}]});this.i=new g.dM(this,250);this.learnMoreButton=
this.Ba("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.Ba("ytp-mdx-manual-pairing-popup-ok");g.F(this,this.i);this.N(this.learnMoreButton,"click",this.l);this.N(this.okButton,"click",this.u)},r9=function(){g.V.call(this,{D:"div",
L:"ytp-mdx-popup-dialog",V:{role:"dialog"},S:[{D:"div",L:"ytp-mdx-popup-dialog-inner-content",S:[{D:"div",L:"ytp-mdx-popup-title",oa:"You're signed out"},{D:"div",L:"ytp-mdx-popup-description",oa:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",L:"ytp-mdx-privacy-popup-buttons",S:[{D:"button",Ca:["ytp-button","ytp-mdx-privacy-popup-cancel"],oa:"Cancel"},{D:"button",Ca:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],oa:"Confirm"}]}]}]});this.i=new g.dM(this,250);this.cancelButton=this.Ba("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Ba("ytp-mdx-privacy-popup-confirm");g.F(this,this.i);this.N(this.cancelButton,"click",this.l);this.N(this.confirmButton,"click",this.u)},s9=function(a){g.V.call(this,{D:"div",
L:"ytp-remote",S:[{D:"div",L:"ytp-remote-display-status",S:[{D:"div",L:"ytp-remote-display-status-icon",S:[g.Hqa()]},{D:"div",L:"ytp-remote-display-status-text",oa:"{{statustext}}"}]}]});this.api=a;this.i=new g.dM(this,250);g.F(this,this.i);this.N(a,"presentingplayerstatechange",this.l);vRa(this,a.sb())},vRa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.U(b,128)?g.cJ("Error on $RECEIVER_NAME",c):b.tc()||g.U(b,4)?g.cJ("Playing on $RECEIVER_NAME",c):g.cJ("Connected to $RECEIVER_NAME",c);a.Sa("statustext",b);a.i.show()}else a.i.hide()},t9=function(a,b){g.pQ.call(this,"Play on",0,a,b);
this.I=a;this.dn={};this.N(a,"onMdxReceiversChange",this.C);this.N(a,"presentingplayerstatechange",this.C);this.C()},u9=function(a){g.yN.call(this,a);
this.Yi={key:M6(),name:"This computer"};this.Jh=null;this.subscriptions=[];this.HC=this.Pb=null;this.dn=[this.Yi];this.im=this.Yi;this.hd=new g.zK(64);this.fI=0;this.Ze=-1;this.Rq=null;this.nu=this.fx=!1;this.El=this.Xq=null;if(!g.SF(this.player.T())&&!g.TF(this.player.T())){a=this.player;var b=g.dN(a);b&&(b=b.Dm())&&(b=new t9(a,b),g.F(this,b));b=new s9(a);g.F(this,b);g.nN(a,b.element,4);this.Xq=new r9;g.F(this,this.Xq);g.nN(a,this.Xq.element,4);g.S(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.S(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.Rq=new q9,g.F(this,this.Rq),g.nN(a,this.Rq.element,4));this.nu=!!a9();this.fx=!!g.jy("yt-remote-manual-pairing-warning-shown")}},v9=function(a){a.El&&(a.player.removeEventListener("presentingplayerstatechange",a.El),a.El=null)},wRa=function(a,b,c){a.hd=c;
a.player.W("presentingplayerstatechange",new g.QI(c,b))},xRa=function(a,b,c){var d=!1;
1===b?d=!a.nu:2===b&&(d=!a.fx);d&&g.SI(c,8)&&(a.player.pauseVideo(),v9(a))},w9=function(a,b){if(b.key!==a.im.key)if(b.key===a.Yi.key)g9();
else{if(a.Rq&&!a.fx&&b!==a.Yi&&"cast-selector-receiver"!==b.key&&g.zG(a.player.T()))yRa(a);else{var c;(c=!g.S(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.O("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.O("SESSION_INDEX")&&!g.O("LOGGED_IN")))||a.nu||!a.Xq);(c?0:g.zG(a.player.T())||g.DG(a.player.T()))&&zRa(a)}a.im=b;if(!a.player.T().Z("disable_mdx_connection_in_mdx_module_for_music_web")||!g.TF(a.player.T())){var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&g.S(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))a=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.gb(l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Ga,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=SOa(c))&&(a.locationInfo=c)}Y8("Connecting to: "+
g.Mh(b));"cast-selector-receiver"==b.key?($8(a||null),b=a||null,t8()?q8().setLaunchParams(b):o8("setLaunchParams called before ready.")):!a&&j9()&&X8()==b.key?G6("yt-remote-connection-change",!0):(g9(),$8(a||null),a=W8().oh(),(b=O6(a,b.key))&&h9(b,1))}}},zRa=function(a){a.player.sb().tc()?a.player.pauseVideo():(a.El=function(b){xRa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.El));
a.Xq&&a.Xq.Vc();d9()||(l9=!0)},yRa=function(a){a.player.sb().tc()?a.player.pauseVideo():(a.El=function(b){xRa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.El));
a.Rq&&a.Rq.Vc();d9()||(l9=!0)},BPa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},m7={"'":"\\'"},YOa={XV:"atp",L5:"ska",C4:"que",K2:"mus",K5:"sus",VZ:"dsp",W4:"seq",m2:"mic",WY:"dpa",lW:"cds",I2:"mlm"},U6,Q6="",rPa=mPa("loadCastFramework")||mPa("loadCastApplicationFramework"),tPa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ta(Z6,g.E);g.k=Z6.prototype;g.k.kN=function(a){this.B=arguments;this.i=!1;this.Gb?this.u=g.Sa()+this.Of:this.Gb=g.ih(this.C,this.Of)};
g.k.stop=function(){this.Gb&&(g.A.clearTimeout(this.Gb),this.Gb=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.G.apply(null,this.B)))};
g.k.ra=function(){this.stop();Z6.Rd.ra.call(this)};
g.k.lN=function(){this.Gb&&(g.A.clearTimeout(this.Gb),this.Gb=null);this.u?(this.Gb=g.ih(this.C,this.u-g.Sa()),this.u=null):this.l?this.i=!0:(this.i=!1,this.G.apply(null,this.B))};g.v($6,g.E);g.k=$6.prototype;g.k.TE=function(a){this.u=arguments;this.Gb||this.l?this.i=!0:a7(this)};
g.k.stop=function(){this.Gb&&(g.A.clearTimeout(this.Gb),this.Gb=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.Gb||(this.i=!1,a7(this))};
g.k.ra=function(){g.E.prototype.ra.call(this);this.stop()};b7.prototype.stringify=function(a){return g.A.JSON.stringify(a,void 0)};
b7.prototype.parse=function(a){return g.A.JSON.parse(a,void 0)};var d7=new g.Hf;g.v(vPa,g.gf);g.k=f7.prototype;g.k.Kn=null;g.k.lj=!1;g.k.Dr=null;g.k.XD=null;g.k.dr=null;g.k.yr=null;g.k.Zl=null;g.k.hn=null;g.k.lp=null;g.k.Qe=null;g.k.Zu=0;g.k.qj=null;g.k.Iy=null;g.k.Vl=null;g.k.Xr=-1;g.k.kK=!0;g.k.Wn=!1;g.k.Dz=0;g.k.Qx=null;var zPa={},i7={};g.k=f7.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.mN=function(a){a=a.target;var b=this.Qx;b&&3==g.Fi(a)?b.TE():this.hL(a)};
g.k.hL=function(a){try{if(a==this.Qe)a:{var b=g.Fi(this.Qe),c=this.Qe.l,d=this.Qe.getStatus();if(g.be&&!g.Wd(10)||g.hg&&!g.Vd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Tk&&!g.Ki(this.Qe))break a;this.Wn||4!=b||7==c||(8==c||0>=d?this.i.aj(3):this.i.aj(2));n7(this);var e=this.Qe.getStatus();this.Xr=e;var f=g.Ki(this.Qe);(this.lj=200==e)?(4==b&&k7(this),this.G?(APa(this,b,f),g.Tk&&this.lj&&3==b&&(this.B.Qa(this.u,"tick",this.RT),this.u.start())):j7(this,f),this.lj&&!this.Wn&&(4==b?this.i.Av(this):
(this.lj=!1,h7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Vl=3,e7(13)):(this.Vl=0,e7(14)),k7(this),l7(this))}}catch(h){this.Qe&&g.Ki(this.Qe)}finally{}};
g.k.RT=function(){var a=g.Fi(this.Qe),b=g.Ki(this.Qe);this.Zu<b.length&&(n7(this),APa(this,a,b),this.lj&&4!=a&&h7(this))};
g.k.zT=function(a){c7((0,g.C)(this.yT,this,a),0)};
g.k.yT=function(a){this.Wn||(n7(this),j7(this,a),h7(this))};
g.k.CJ=function(a){c7((0,g.C)(this.xT,this,a),0)};
g.k.xT=function(a){this.Wn||(k7(this),this.lj=a,this.i.Av(this),this.i.aj(4))};
g.k.cancel=function(){this.Wn=!0;k7(this)};
g.k.HT=function(){this.Dr=null;var a=Date.now();0<=a-this.XD?(2!=this.yr&&this.i.aj(3),k7(this),this.Vl=2,e7(18),l7(this)):DPa(this,this.XD-a)};
g.k.getLastError=function(){return this.Vl};g.k=GPa.prototype;g.k.Ez=null;g.k.Yg=null;g.k.Rx=!1;g.k.wK=null;g.k.bw=null;g.k.RB=null;g.k.Fz=null;g.k.Oa=null;g.k.Dk=-1;g.k.Yr=null;g.k.ys=null;g.k.connect=function(a){this.Fz=a;a=p7(this.i,null,this.Fz);e7(3);this.wK=Date.now();var b=this.i.J;null!=b?(this.Yr=b[0],(this.ys=b[1])?(this.Oa=1,HPa(this)):(this.Oa=2,r7(this))):(D6(a,"MODE","init"),this.Yg=new f7(this,void 0,void 0,void 0),this.Yg.Kn=this.Ez,g7(this.Yg,a,!1,null,!0),this.Oa=0)};
g.k.iO=function(a){if(a)this.Oa=2,r7(this);else{e7(4);var b=this.i;b.Fj=b.gm.Dk;y7(b,9)}a&&this.aj(2)};
g.k.IA=function(a){return this.i.IA(a)};
g.k.abort=function(){this.Yg&&(this.Yg.cancel(),this.Yg=null);this.Dk=-1};
g.k.We=function(){return!1};
g.k.vJ=function(a,b){this.Dk=a.Xr;if(0==this.Oa)if(b){try{var c=this.l.parse(b)}catch(d){a=this.i;a.Fj=this.Dk;y7(a,2);return}this.Yr=c[0];this.ys=c[1]}else a=this.i,a.Fj=this.Dk,y7(a,2);else if(2==this.Oa)if(this.Rx)e7(7),this.RB=Date.now();else if("11111"==b){if(e7(6),this.Rx=!0,this.bw=Date.now(),a=this.bw-this.wK,!g.be||g.Wd(10)||500>a)this.Dk=200,this.Yg.cancel(),e7(12),q7(this.i,this,!0)}else e7(8),this.bw=this.RB=Date.now(),this.Rx=!1};
g.k.Av=function(){this.Dk=this.Yg.Xr;if(this.Yg.lj)0==this.Oa?this.ys?(this.Oa=1,HPa(this)):(this.Oa=2,r7(this)):2==this.Oa&&((!g.be||g.Wd(10)?!this.Rx:200>this.RB-this.bw)?(e7(11),q7(this.i,this,!1)):(e7(12),q7(this.i,this,!0)));else{0==this.Oa?e7(9):2==this.Oa&&e7(10);var a=this.i;this.Yg.getLastError();a.Fj=this.Dk;y7(a,2)}};
g.k.Hu=function(){return this.i.Hu()};
g.k.isActive=function(){return this.i.isActive()};
g.k.aj=function(a){this.i.aj(a)};g.k=s7.prototype;g.k.Ej=null;g.k.Ps=null;g.k.Mg=null;g.k.oe=null;g.k.Gz=null;g.k.cw=null;g.k.cG=null;g.k.Bv=null;g.k.Rt=0;g.k.rQ=0;g.k.Kf=null;g.k.qm=null;g.k.Tk=null;g.k.uo=null;g.k.gm=null;g.k.Gy=null;g.k.Mq=-1;g.k.eI=-1;g.k.Fj=-1;g.k.xq=0;g.k.gq=0;g.k.Xn=8;g.Ta(JPa,g.gf);g.Ta(KPa,g.gf);g.k=s7.prototype;g.k.connect=function(a,b,c,d,e){e7(0);this.Gz=b;this.Ps=c||{};d&&void 0!==e&&(this.Ps.OSID=d,this.Ps.OAID=e);this.C?(c7((0,g.C)(this.vG,this,a),100),OPa(this)):this.vG(a)};
g.k.vG=function(a){this.gm=new GPa(this);this.gm.Ez=this.Ej;this.gm.l=this.B;this.gm.connect(a)};
g.k.We=function(){return 0==this.Oa};
g.k.getState=function(){return this.Oa};
g.k.AJ=function(a){this.qm=null;SPa(this,a)};
g.k.zJ=function(){this.Tk=null;this.oe=new f7(this,this.l,"rpc",this.G);this.oe.Kn=this.Ej;this.oe.Dz=0;var a=this.cG.clone();g.ok(a,"RID","rpc");g.ok(a,"SID",this.l);g.ok(a,"CI",this.Gy?"0":"1");g.ok(a,"AID",this.Mq);t7(this,a);if(!g.be||g.Wd(10))g.ok(a,"TYPE","xmlhttp"),g7(this.oe,a,!0,this.Bv,!1);else{g.ok(a,"TYPE","html");var b=this.oe,c=!!this.Bv;b.yr=3;b.Zl=C6(a.clone());CPa(b,c)}};
g.k.vJ=function(a,b){if(0!=this.Oa&&(this.oe==a||this.Mg==a))if(this.Fj=a.Xr,this.Mg==a&&3==this.Oa)if(7<this.Xn){try{var c=this.B.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.Tk){if(this.oe)if(this.oe.dr+3E3<this.Mg.dr)v7(this),this.oe.cancel(),this.oe=null;else break a;x7(this);e7(19)}}else this.eI=a[1],0<this.eI-this.Mq&&37500>a[2]&&this.Gy&&0==this.gq&&!this.uo&&(this.uo=c7((0,g.C)(this.UQ,this),6E3));else y7(this,11)}else null!=b&&y7(this,11);else if(this.oe==
a&&v7(this),!g.qc(b))for(a=this.B.parse(b),b=0;b<a.length;b++)c=a[b],this.Mq=c[0],c=c[1],2==this.Oa?"c"==c[0]?(this.l=c[1],this.Bv=c[2],c=c[3],null!=c?this.Xn=c:this.Xn=6,this.Oa=3,this.Kf&&this.Kf.rG(),this.cG=p7(this,this.Hu()?this.Bv:null,this.Gz),TPa(this)):"stop"==c[0]&&y7(this,7):3==this.Oa&&("stop"==c[0]?y7(this,7):"noop"!=c[0]&&this.Kf&&this.Kf.qG(c),this.gq=0)};
g.k.UQ=function(){null!=this.uo&&(this.uo=null,this.oe.cancel(),this.oe=null,x7(this),e7(20))};
g.k.Av=function(a){if(this.oe==a){v7(this);this.oe=null;var b=2}else if(this.Mg==a)this.Mg=null,b=1;else return;this.Fj=a.Xr;if(0!=this.Oa)if(a.lj)if(1==b){b=Date.now()-a.dr;var c=d7;c.dispatchEvent(new JPa(c,a.lp?a.lp.length:0,b,this.xq));u7(this);this.u.length=0}else TPa(this);else{c=a.getLastError();var d;if(!(d=3==c||7==c||0==c&&0<this.Fj)){if(d=1==b)this.Mg||this.qm||1==this.Oa||2<=this.xq?d=!1:(this.qm=c7((0,g.C)(this.AJ,this,a),UPa(this,this.xq)),this.xq++,d=!0);d=!(d||2==b&&x7(this))}if(d)switch(c){case 1:y7(this,
5);break;case 4:y7(this,10);break;case 3:y7(this,6);break;case 7:y7(this,12);break;default:y7(this,2)}}};
g.k.IO=function(a){if(!g.jb(arguments,this.Oa))throw Error("Unexpected channel state: "+this.Oa);};
g.k.HU=function(a){a?e7(2):(e7(1),VPa(this,8))};
g.k.IA=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.zi;a.K=!1;return a};
g.k.isActive=function(){return!!this.Kf&&this.Kf.isActive(this)};
g.k.aj=function(a){var b=d7;b.dispatchEvent(new KPa(b,a))};
g.k.Hu=function(){return!(!g.be||g.Wd(10))};
g.k=WPa.prototype;g.k.rG=function(){};
g.k.qG=function(){};
g.k.pG=function(){};
g.k.vA=function(){};
g.k.bH=function(){return{}};
g.k.isActive=function(){return!0};g.k=XPa.prototype;g.k.isEmpty=function(){return 0===this.i.length&&0===this.l.length};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.jb(this.i,a)||g.jb(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.kJa)(b,a);0<=c?(g.lb(b,c),b=!0):b=!1;return b||g.nb(this.l,a)};
g.k.Og=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Ta(z7,g.E);g.k=z7.prototype;g.k.rT=function(){this.Of=Math.min(3E5,2*this.Of);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Of+15E3*Math.random();g.Dq(this.i,a);this.l=Date.now()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Of=5E3};g.Ta(A7,WPa);g.k=A7.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Uf=function(a){return this.u.Uf(a)};
g.k.W=function(a,b){return this.u.W.apply(this.u,arguments)};
g.k.dispose=function(){this.Y||(this.Y=!0,g.df(this.u),$Pa(this),g.df(this.l),this.l=null,this.X=function(){return""})};
g.k.Ha=function(){return this.Y};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.U="";this.l.stop();this.C=a||null;this.B=b||0;a=this.ma+"/test";b=this.ma+"/bind";var d=new s7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.va),e=this.i;e&&(e.Kf=null);d.Kf=this;this.i=d;B7(this);if(this.i){d=g.O("ID_TOKEN");var f=this.i.Ej||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Ej=f}e?(3!=e.getState()&&0==QPa(e)||e.getState(),this.i.connect(a,b,this.G,e.l,e.Mq)):c?this.i.connect(a,
b,this.G,c.sessionId,c.arrayId):this.i.connect(a,b,this.G)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.Xb(a,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.J.push(a):C7(this)&&(B7(this),PPa(this.i,a))};
g.k.rG=function(){this.l.reset();this.C=null;this.B=0;if(this.J.length){var a=this.J;this.J=[];for(var b=0,c=a.length;b<c;++b)PPa(this.i,a[b])}this.W("handlerOpened")};
g.k.pG=function(a){var b=2==a&&401==this.i.Fj;4==a||b||this.l.start();this.W("handlerError",a,b)};
g.k.vA=function(a){if(!this.l.isActive())this.W("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.J.push(d)}};
g.k.bH=function(){var a={v:2};this.U&&(a.gsessionid=this.U);0!=this.B&&(a.ui=""+this.B);0!=this.K&&(a.ui=""+this.K);this.C&&g.Xb(a,this.C);return a};
g.k.qG=function(a){"S"==a[0]?this.U=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),NPa(this.i)):this.W("handlerMessage",new YPa(a[0],a[1]))};
g.k.ey=function(a){(this.G.loungeIdToken=a)||this.l.stop();if(this.xa&&this.i){var b=this.i.Ej||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Ej=b}};
g.k.mU=function(){this.l.isActive();0==QPa(this.i)&&this.connect(this.C,this.B)};D7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
D7.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
D7.prototype.C=function(a){a(Error("request timed out"))};var gQa=Date.now(),G7=null,J7=Array(50),I7=-1,K7=!1;g.Ta(L7,g.Q);L7.prototype.oh=function(){return this.screens};
L7.prototype.contains=function(a){return!!N6(this.screens,a)};
L7.prototype.get=function(a){return a?O6(this.screens,a):null};
L7.prototype.info=function(a){H7(this.G,a)};g.v(M7,g.Q);g.k=M7.prototype;g.k.start=function(){!this.i&&isNaN(this.Gb)&&this.IJ()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.Gb)||(g.ls(this.Gb),this.Gb=NaN)};
g.k.ra=function(){this.stop();g.Q.prototype.ra.call(this)};
g.k.IJ=function(){this.Gb=NaN;this.i=g.qs(E7(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.J},timeout:5E3,onSuccess:(0,g.C)(this.oN,this),onError:(0,g.C)(this.nN,this),onTimeout:(0,g.C)(this.pN,this)})};
g.k.oN=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.B;a.name=this.G;b=-1;this.C&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.W("pairingComplete",new I6(a),b)};
g.k.nN=function(a){this.i=null;a.status&&404==a.status?this.l>=ARa.length?this.W("pairingFailed",Error("DIAL polling timed out")):(a=ARa[this.l],this.Gb=g.js((0,g.C)(this.IJ,this),a),this.l++):this.W("pairingFailed",Error("Server error "+a.status))};
g.k.pN=function(){this.i=null;this.W("pairingFailed",Error("Server not responding"))};
var ARa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(O7,L7);g.k=O7.prototype;g.k.start=function(){N7(this)&&this.W("screenChange");!g.jy("yt-remote-lounge-token-expiration")&&kQa(this);g.ls(this.i);this.i=g.js((0,g.C)(this.start,this),1E4)};
g.k.add=function(a,b){N7(this);hQa(this,a);P7(this,!1);this.W("screenChange");b(a);a.token||kQa(this)};
g.k.remove=function(a,b){var c=N7(this);jQa(this,a)&&(P7(this,!1),c=!0);b(a);c&&this.W("screenChange")};
g.k.Ey=function(a,b,c,d){var e=N7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,P7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.W("screenChange")};
g.k.ra=function(){g.ls(this.i);O7.Rd.ra.call(this)};
g.k.hP=function(a){N7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}P7(this,!b);b&&H7(this.G,"Missed "+b+" lounge tokens.")};
g.k.gP=function(a){H7(this.G,"Requesting lounge tokens failed: "+a)};g.v(R7,g.Q);g.k=R7.prototype;g.k.start=function(){var a=parseInt(g.jy("yt-remote-fast-check-period")||"0",10);(this.B=g.Sa()-144E5<a?0:a)?U7(this):(this.B=g.Sa()+3E5,g.iy("yt-remote-fast-check-period",this.B),this.VC())};
g.k.isEmpty=function(){return g.Qb(this.i)};
g.k.update=function(){Q7("Updating availability on schedule.");var a=this.G(),b=g.Eb(this.i,function(c,d){return c&&!!O6(a,d)},this);
T7(this,b)};
g.k.ra=function(){g.ls(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.Q.prototype.ra.call(this)};
g.k.VC=function(){g.ls(this.u);this.u=NaN;this.l&&this.l.abort();var a=mQa(this);if(E6(a)){var b=E7(this.C,"/pairing/get_screen_availability");this.l=F7(this.C,b,{lounge_token:g.Lb(a).join(",")},(0,g.C)(this.XS,this,a),(0,g.C)(this.WS,this))}else T7(this,{}),U7(this)};
g.k.XS=function(a,b){this.l=null;var c=g.Lb(mQa(this));if(g.zb(c,g.Lb(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;T7(this,c);U7(this)}else this.Sd("Changing Screen set during request."),this.VC()};
g.k.WS=function(a){this.Sd("Screen availability failed: "+a);this.l=null;U7(this)};
g.k.Sd=function(a){H7("OnlineScreenService",a)};g.Ta(V7,L7);g.k=V7.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.W("screenChange"),this.i.isEmpty()||this.W("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.Ey=function(a,b,c,d){this.l.contains(a)?this.l.Ey(a,b,c,d):(a="Updating name of unknown screen: "+a.name,H7(this.G,a),d(Error(a)))};
g.k.oh=function(a){return a?this.screens:g.pb(this.screens,g.Po(this.u,function(b){return!this.contains(b)},this))};
g.k.UE=function(){return g.Po(this.oh(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.VE=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new M7(this.B,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.df(l);e(W7(h,m),n)});
l.subscribe("pairingFailed",function(m){g.df(l);f(m)});
l.start();return(0,g.C)(l.stop,l)};
g.k.qN=function(a,b,c,d){g.qs(E7(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.C)(function(e,f){e=new I6(f.screen||{});if(!e.name||qQa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);qQa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(W7(this,e))},this),
onError:(0,g.C)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.C)(function(){d(Error("pairing request timed out."))},this)})};
g.k.ra=function(){g.df(this.l);g.df(this.i);V7.Rd.ra.call(this)};
g.k.qP=function(){sQa(this);this.W("screenChange");this.i.update()};
V7.prototype.dispose=V7.prototype.dispose;g.Ta(Y7,g.Q);g.k=Y7.prototype;g.k.getScreen=function(){return this.B};
g.k.pg=function(a){this.Ha()||(a&&$7(this,""+a),this.B=null,this.W("sessionScreen",null))};
g.k.info=function(a){H7(this.xa,a)};
g.k.WE=function(){return null};
g.k.gD=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.C)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.C)(function(){$7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.ra=function(){this.gD("");Y7.Rd.ra.call(this)};g.v(a8,Y7);g.k=a8.prototype;g.k.fD=function(a){if(this.l){if(this.l==a)return;$7(this,"Overriding cast session with new session object");BQa(this);this.ma=!1;this.U="unknown";this.l.removeUpdateListener(this.X);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.va)}this.l=a;this.l.addUpdateListener(this.X);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.va);xQa(this,"getMdxSessionStatus")};
g.k.Nq=function(a){this.info("launchWithParams no-op for Cast: "+g.Mh(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.C)(function(){this.pg()},this),(0,g.C)(function(){this.pg(Error("Failed to stop receiver app."))},this)):this.pg(Error("Stopping cast device without session."))};
g.k.gD=function(){};
g.k.ra=function(){this.info("disposeInternal");BQa(this);this.l&&(this.l.removeUpdateListener(this.X),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.va));this.l=null;Y7.prototype.ra.call(this)};
g.k.KT=function(a,b){if(!this.Ha())if(b)if(b=F6(b),g.Na(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Mh(b)),a){case "mdxSessionStatus":vQa(this,b);break;case "loungeToken":yQa(this,b);break;default:$7(this,"Unknown youtube message: "+a)}else $7(this,"Unable to parse message.");else $7(this,"No data in message.")};
g.k.qH=function(a,b,c,d){g.ls(this.K);this.K=0;pQa(this.u,this.i.label,a,this.i.friendlyName,(0,g.C)(function(e){e?b(e):0<=d?($7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.K=g.js((0,g.C)(this.qH,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.WE=function(){return this.l};
g.k.rN=function(a){this.Ha()||a||($7(this,"Cast session died."),this.pg())};g.v(d8,Y7);g.k=d8.prototype;g.k.fD=function(a){this.l=a;this.l.addUpdateListener(this.Aa)};
g.k.Nq=function(a){this.Ea=a;this.Y()};
g.k.stop=function(){IQa(this);this.l?this.l.stop((0,g.C)(this.pg,this,null),(0,g.C)(this.pg,this,"Failed to stop DIAL device.")):this.pg()};
g.k.ra=function(){IQa(this);this.l&&this.l.removeUpdateListener(this.Aa);this.l=null;Y7.prototype.ra.call(this)};
g.k.sN=function(a){this.Ha()||a||($7(this,"DIAL session died."),this.C(),this.C=g.Ja,this.pg())};g.v(h8,Y7);h8.prototype.stop=function(){this.pg()};
h8.prototype.fD=function(){};
h8.prototype.Nq=function(){g.ls(this.l);this.l=NaN;var a=O6(this.u.oh(),this.i.label);a?Z7(this,a):this.pg(Error("No such screen"))};
h8.prototype.ra=function(){g.ls(this.l);this.l=NaN;Y7.prototype.ra.call(this)};g.v(i8,g.Q);g.k=i8.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.J);this.K||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a||this.U?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.C)(this.GS,this);c=new chrome.cast.ApiConfig(c,(0,g.C)(this.wJ,this),e,d,a);c.customDialLaunchCallback=(0,g.C)(this.pR,this);chrome.cast.initialize(c,(0,g.C)(function(){this.Ha()||
(chrome.cast.addReceiverActionListener(this.C),dQa(),this.l.subscribe("onlineScreenChange",(0,g.C)(this.XE,this)),this.u=KQa(this),chrome.cast.setCustomReceivers(this.u,g.Ja,(0,g.C)(function(f){this.Sd("Failed to set initial custom receivers: "+g.Mh(f))},this)),this.W("yt-remote-cast2-availability-change",k8(this)),b(!0))},this),(0,g.C)(function(f){this.Sd("Failed to initialize API: "+g.Mh(f));
b(!1)},this))};
g.k.sU=function(a,b){j8("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)j8("Unsetting old screen status: "+this.i.i.friendlyName),l8(this,null)}if(a&&b){if(!this.i){c=O6(this.l.oh(),a);if(!c){j8("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){j8("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=JQa(this,c);a||(j8("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(a),chrome.cast.setCustomReceivers(this.u,g.Ja,(0,g.C)(function(d){this.Sd("Failed to set initial custom receivers: "+g.Mh(d))},this)));
j8("setConnectedScreenStatus: new active receiver: "+a.friendlyName);l8(this,new h8(this.l,a),!0)}this.i.gD(b)}else j8("setConnectedScreenStatus: no screen.")};
g.k.tU=function(a){this.Ha()?this.Sd("Setting connection data on disposed cast v2"):this.i?this.i.Nq(a):this.Sd("Setting connection data without a session")};
g.k.uN=function(){this.Ha()?this.Sd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),l8(this,null)):j8("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.C)(this.wJ,this),(0,g.C)(this.aT,this))};
g.k.ra=function(){this.l.unsubscribe("onlineScreenChange",(0,g.C)(this.XE,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.C);var a=aQa,b=g.Ia("yt.mdx.remote.debug.handlers_");g.nb(b||[],a);g.df(this.i);g.Q.prototype.ra.call(this)};
g.k.Sd=function(a){H7("Controller",a)};
g.k.yJ=function(a,b){this.i==a&&(b||l8(this,null),this.W("yt-remote-cast2-session-change",b))};
g.k.CS=function(a,b){if(!this.Ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),j8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)j8("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{j8("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.W("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:l8(this,
new h8(this.l,a));break;case chrome.cast.ReceiverType.DIAL:l8(this,new d8(this.l,a,this.B,this.config_));break;case chrome.cast.ReceiverType.CAST:l8(this,new a8(this.l,a,this.config_));break;default:this.Sd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Sd("Stopping receiver w/o session: "+a.friendlyName)}else this.Sd("onReceiverAction_ called without receiver.")};
g.k.pR=function(a){if(this.Ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Sd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Sd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return j8("Reselecting dial screen."),
this.W("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Sd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);l8(this,new d8(this.l,b,this.B,this.config_))}b=this.i;b.K=a;b.K.appState==chrome.cast.DialAppState.RUNNING?(a=b.K.extraData||{},c=a.screenId||null,e8(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=FQa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.K.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.Pr(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=GQa(b,c)):a=GQa(b,c)):a=g8(b);return a};
g.k.wJ=function(a){if(!this.Ha()){j8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(b.receiverType==chrome.cast.ReceiverType.CAST)j8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),l8(this,new a8(this.l,b,this.config_),!0);else{this.Sd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.i.i,d=O6(this.l.oh(),c.label);d&&J6(d,
b.label)&&c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(j8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.df(this.i),this.i=new a8(this.l,b,this.config_),this.i.subscribe("sessionScreen",(0,g.C)(this.yJ,this,this.i)),this.i.Nq(null));this.i.fD(a)}}};
g.k.tN=function(){return this.i?this.i.WE():null};
g.k.aT=function(a){this.Ha()||(this.Sd("Failed to estabilish a session: "+g.Mh(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&l8(this,null))};
g.k.GS=function(a){j8("Receiver availability updated: "+a);if(!this.Ha()){var b=k8(this);this.G=a==chrome.cast.ReceiverAvailability.AVAILABLE;k8(this)!=b&&this.W("yt-remote-cast2-availability-change",k8(this))}};
g.k.XE=function(){this.Ha()||(this.u=KQa(this),j8("Updating custom receivers: "+g.Mh(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ja,(0,g.C)(function(){this.Sd("Failed to set custom receivers.")},this)),this.W("yt-remote-cast2-availability-change",k8(this)))};
i8.prototype.setLaunchParams=i8.prototype.tU;i8.prototype.setConnectedScreenStatus=i8.prototype.sU;i8.prototype.stopSession=i8.prototype.uN;i8.prototype.getCastSession=i8.prototype.tN;i8.prototype.requestSession=i8.prototype.requestSession;i8.prototype.init=i8.prototype.init;i8.prototype.dispose=i8.prototype.dispose;var r8=[];g.k=w8.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";x8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Uj=a.hasPrevious,this.hasNext=a.hasNext,this.J=a.playerTime,this.G=a.playerTimeAt,this.B=a.seekableStart,this.i=a.seekableEnd,this.C=a.duration,this.K=a.loadedTime,this.u=a.liveIngestionTime,this.l=
!isNaN(this.u))};
g.k.tc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.l?this.C+y8(this):this.C};
g.k.clone=function(){return new w8(C8(this))};g.v(E8,g.Q);g.k=E8.prototype;g.k.getState=function(){return this.Oa};
g.k.play=function(){G8(this)?(this.i?this.i.play(null,g.Ja,L8(this,"play")):K8(this,"play"),J8(this,1,A8(F8(this))),this.W("remotePlayerChange")):H8(this,this.play)};
g.k.pause=function(){G8(this)?(this.i?this.i.pause(null,g.Ja,L8(this,"pause")):K8(this,"pause"),J8(this,2,A8(F8(this))),this.W("remotePlayerChange")):H8(this,this.pause)};
g.k.seekTo=function(a){if(G8(this)){if(this.i){var b=F8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.tc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ja,L8(this,"seekTo",{newTime:a}))}else K8(this,"seekTo",{newTime:a});J8(this,3,a);this.W("remotePlayerChange")}else H8(this,g.Qa(this.seekTo,a))};
g.k.stop=function(){if(G8(this)){this.i?this.i.stop(null,g.Ja,L8(this,"stopVideo")):K8(this,"stopVideo");var a=F8(this);a.index=-1;a.videoId="";x8(a);I8(this,a);this.W("remotePlayerChange")}else H8(this,this.stop)};
g.k.setVolume=function(a,b){if(G8(this)){var c=F8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.C)(function(){H7("CP","set receiver volume: "+d)},this),(0,g.C)(function(){this.Sd("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.C)(function(){H7("CP","set receiver muted: "+b)},this),(0,g.C)(function(){this.Sd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);K8(this,"setVolume",e)}c.muted=b;c.volume=a;I8(this,c)}else H8(this,g.Qa(this.setVolume,a,b))};
g.k.YE=function(a,b){if(G8(this)){var c=F8(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Mh(b.style),g.Xb(a,c.trackData));K8(this,"setSubtitlesTrack",a);I8(this,c)}else H8(this,g.Qa(this.YE,a,b))};
g.k.setAudioTrack=function(a,b){G8(this)?(b=b.getLanguageInfo().getId(),K8(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=F8(this),a.audioTrackId=b,I8(this,a)):H8(this,g.Qa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){d=void 0===d?null:d;e=void 0===e?null:e;f=void 0===f?null:f;h=void 0===h?null:h;var l=F8(this),m={videoId:a};void 0!==c&&(m.currentIndex=c);B8(l,a,c||0);void 0!==b&&(z8(l,b),m.currentTime=b);d&&(m.listId=d);e&&(m.playerParams=e);f&&(m.clickTrackingParams=f);h&&(m.locationInfo=g.Mh(h));K8(this,"setPlaylist",m);d||I8(this,l)};
g.k.Mx=function(a,b){if(G8(this)){if(a&&b){var c=F8(this);B8(c,a,b);I8(this,c)}K8(this,"previous")}else H8(this,g.Qa(this.Mx,a,b))};
g.k.nextVideo=function(a,b){if(G8(this)){if(a&&b){var c=F8(this);B8(c,a,b);I8(this,c)}K8(this,"next")}else H8(this,g.Qa(this.nextVideo,a,b))};
g.k.IG=function(){G8(this)?K8(this,"dismissAutoplay"):H8(this,this.IG)};
g.k.dispose=function(){if(3!=this.Oa){var a=this.Oa;this.Oa=3;this.W("proxyStateChange",a,this.Oa)}g.Q.prototype.dispose.call(this)};
g.k.ra=function(){WQa(this);this.u=null;this.B.clear();D8(this,null);g.Q.prototype.ra.call(this)};
g.k.iD=function(a){if((a!=this.Oa||2==a)&&3!=this.Oa&&0!=a){var b=this.Oa;this.Oa=a;this.W("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,0===b.i.length&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.zS=function(a,b){this.W(a,b)};
g.k.aR=function(a){if(!a)this.Vt(null),D8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=F8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)H7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,I8(this,b)}};
g.k.Vt=function(a){H7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.J);if(this.i=a)this.i.addUpdateListener(this.J),XQa(this),this.W("remotePlayerChange")};
g.k.ZQ=function(a){a?(XQa(this),this.W("remotePlayerChange")):this.Vt(null)};
g.k.BD=function(){K8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.hR=function(){var a=TQa();a&&D8(this,a)};
g.k.Sd=function(a){H7("CP",a)};g.v(M8,g.Q);g.k=M8.prototype;
g.k.connect=function(a,b,c){c=void 0===c?!1:c;if(b){var d=b.listId,e=b.videoId,f=b.videoIds,h=b.playerParams,l=b.clickTrackingParams,m=b.index,n={videoId:e},p=b.currentTime,r=b.locationInfo;b=b.loopMode;void 0!==p&&(n.currentTime=5>=p?0:p);h&&(n.playerParams=h);r&&(n.locationInfo=r);l&&(n.clickTrackingParams=l);d&&(n.listId=d);f&&0<f.length&&(n.videoIds=f.join(","));void 0!==m&&(n.currentIndex=m);c&&(n.loopMode=b||"LOOP_MODE_OFF");d&&(this.dc.listId=d);this.dc.videoId=e;this.dc.index=m||0;this.dc.state=
3;z8(this.dc,p);this.B="UNSUPPORTED";c=c?"setInitialState":"setPlaylist";N8("Connecting with "+c+" and params: "+g.Mh(n));this.i.connect({method:c,params:g.Mh(n)},a,fPa())}else N8("Connecting without params"),this.i.connect({},a,fPa());ZQa(this)};
g.k.ey=function(a){this.i.ey(a)};
g.k.dispose=function(){this.Ha()||(this.W("beforeDispose"),O8(this,3));g.Q.prototype.dispose.call(this)};
g.k.ra=function(){P8(this);R8(this);Q8(this);g.ls(this.J);this.J=NaN;g.ls(this.K);this.K=NaN;this.u=null;g.Mt(this.U);this.U.length=0;this.i.dispose();g.Q.prototype.ra.call(this);this.B=this.G=this.l=this.dc=this.i=null};
g.k.cP=function(){this.rq(2)};
g.k.eR=function(){N8("Channel opened");this.ma&&(this.ma=!1,Q8(this),this.X=g.js((0,g.C)(function(){N8("Timing out waiting for a screen.");this.rq(1)},this),15E3));
jPa(ZPa(this.i),this.Aa)};
g.k.bR=function(){N8("Channel closed");isNaN(this.C)?T6(!0):T6();this.dispose()};
g.k.cR=function(a,b){T6();isNaN(this.ot())?(b&&"shortLived"==this.va&&this.W("browserChannelAuthError",a),N8("Channel error: "+a+" without reconnection"),this.dispose()):(this.ma=!0,N8("Channel error: "+a+" with reconnection in "+this.ot()+" ms"),O8(this,2))};
g.k.dR=function(a){a.params?N8("Received: action="+a.action+", params="+g.Mh(a.params)):N8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=F6(a.params.devices);this.l=g.Oe(a,function(c){return new H6(c)});
a=!!g.fb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
bRa(this,a);break;case "loungeScreenDisconnected":g.ob(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
bRa(this,!1);break;case "remoteConnected":var b=new H6(F6(a.params.device));g.fb(this.l,function(c){return b?c.id==b.id:!1})||TOa(this.l,b);
break;case "remoteDisconnected":b=new H6(F6(a.params.device));g.ob(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":dRa(this,a);break;case "nowPlaying":fRa(this,a);break;case "onStateChange":eRa(this,a);break;case "onAdStateChange":gRa(this,a);break;case "onVolumeChanged":hRa(this,a);break;case "onSubtitlesTrackChanged":cRa(this,a);break;case "nowAutoplaying":iRa(this,a);break;case "autoplayDismissed":this.W("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.W("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.W("autoplayModeChange",this.B);"DISABLED"==this.B&&this.W("autoplayDismissed");break;case "onHasPreviousNextChanged":jRa(this,a);break;case "requestAssistedSignIn":this.W("assistedSignInRequested",a.params.authCode);break;case "onLoopModeChanged":this.W("loopModeChange",a.params.loopMode);break;default:N8("Unrecognized action: "+a.action)}};
g.k.gU=function(){if(this.u){var a=this.u;this.u=null;this.dc.videoId!=a&&S8(this,"getNowPlaying")}};
g.k.XO=function(){var a=3;this.Ha()||(a=0,isNaN(this.ot())?C7(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.rq=function(a){N8("Disconnecting with "+a);P8(this);this.W("beforeDisconnect",a);1==a&&T6();$Pa(this.i,a);this.dispose()};
g.k.VO=function(){var a=this.dc;this.u&&(a=this.dc.clone(),B8(a,this.u,a.index));return C8(a)};
g.k.uU=function(a){var b=new w8(a);b.videoId&&b.videoId!=this.dc.videoId&&(this.u=b.videoId,g.ls(this.J),this.J=g.js((0,g.C)(this.gU,this),5E3));var c=[];this.dc.listId==b.listId&&this.dc.videoId==b.videoId&&this.dc.index==b.index||c.push("remoteQueueChange");this.dc.playerState==b.playerState&&this.dc.volume==b.volume&&this.dc.muted==b.muted&&A8(this.dc)==A8(b)&&g.Mh(this.dc.trackData)==g.Mh(b.trackData)||c.push("remotePlayerChange");this.dc.reset(a);g.Bb(c,function(d){this.W(d)},this)};
g.k.oH=function(){var a=this.i.G.id,b=g.fb(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.ot=function(){var a=this.i;return a.l.isActive()?a.l.l-Date.now():NaN};
g.k.SO=function(){return this.B||"UNSUPPORTED"};
g.k.TO=function(){return this.G||""};
g.k.vN=function(){if(!isNaN(this.ot())){var a=this.i.l;g.Eq(a.i);a.start()}};
g.k.rU=function(a,b){S8(this,a,b);aRa(this)};
g.k.ZE=function(){var a=g.Ys("SID","")||"",b=g.Ys("SAPISID","")||"",c=g.Ys("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.Zd(g.Ya(a),2);b=g.Zd(g.Ya(b),2);c=g.Zd(g.Ya(c),2);return g.Zd(g.Ya(a+","+b+","+c),2)};
M8.prototype.subscribe=M8.prototype.subscribe;M8.prototype.unsubscribeByKey=M8.prototype.Uf;M8.prototype.getProxyState=M8.prototype.XO;M8.prototype.disconnect=M8.prototype.rq;M8.prototype.getPlayerContextData=M8.prototype.VO;M8.prototype.setPlayerContextData=M8.prototype.uU;M8.prototype.getOtherConnectedRemoteId=M8.prototype.oH;M8.prototype.getReconnectTimeout=M8.prototype.ot;M8.prototype.getAutoplayMode=M8.prototype.SO;M8.prototype.getAutoplayVideoId=M8.prototype.TO;M8.prototype.reconnect=M8.prototype.vN;
M8.prototype.sendMessage=M8.prototype.rU;M8.prototype.getXsrfToken=M8.prototype.ZE;g.v(T8,L7);g.k=T8.prototype;g.k.oh=function(a){return this.ye.$_gs(a)};
g.k.contains=function(a){return!!this.ye.$_c(a)};
g.k.get=function(a){return this.ye.$_g(a)};
g.k.start=function(){this.ye.$_st()};
g.k.add=function(a,b,c){this.ye.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.ye.$_r(a,b,c)};
g.k.Ey=function(a,b,c,d){this.ye.$_un(a,b,c,d)};
g.k.ra=function(){for(var a=0,b=this.i.length;a<b;++a)this.ye.$_ubk(this.i[a]);this.i.length=0;this.ye=null;L7.prototype.ra.call(this)};
g.k.wN=function(){this.W("screenChange")};
g.k.gS=function(){this.W("onlineScreenChange")};
V7.prototype.$_st=V7.prototype.start;V7.prototype.$_gspc=V7.prototype.qN;V7.prototype.$_gsppc=V7.prototype.VE;V7.prototype.$_c=V7.prototype.contains;V7.prototype.$_g=V7.prototype.get;V7.prototype.$_a=V7.prototype.add;V7.prototype.$_un=V7.prototype.Ey;V7.prototype.$_r=V7.prototype.remove;V7.prototype.$_gs=V7.prototype.oh;V7.prototype.$_gos=V7.prototype.UE;V7.prototype.$_s=V7.prototype.subscribe;V7.prototype.$_ubk=V7.prototype.Uf;var f9=null,l9=!1,U8=null,V8=null,k9=null,Z8=[];g.v(m9,g.E);g.k=m9.prototype;g.k.ra=function(){g.E.prototype.ra.call(this);this.i.stop();this.u.stop();this.K.stop();this.X();var a=this.Pb;a.unsubscribe("proxyStateChange",this.uJ,this);a.unsubscribe("remotePlayerChange",this.au,this);a.unsubscribe("remoteQueueChange",this.Hx,this);a.unsubscribe("previousNextChange",this.rJ,this);a.unsubscribe("nowAutoplaying",this.lJ,this);a.unsubscribe("autoplayDismissed",this.LI,this);this.Pb=this.l=null};
g.k.Ui=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Pb.Oa)if(n9(this)){if(!F8(this.Pb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":F8(this.Pb).tc()?this.Pb.pause():this.Pb.play();break;case "control_play":this.Pb.play();break;case "control_pause":this.Pb.pause();break;case "control_seek":this.J.TE(c[0],c[1]);break;case "control_subtitles_set_track":o9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.I.getCurrentTime();p9(this,0===c?void 0:c);break;case "control_seek":p9(this,c[0]);break;case "control_subtitles_set_track":o9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.XQ=function(a){this.K.kN(a)};
g.k.ZU=function(a){this.Ui("control_subtitles_set_track",g.Qb(a)?null:a)};
g.k.BK=function(){var a=this.I.getOption("captions","track");g.Qb(a)||o9(this,a)};
g.k.Rb=function(a){this.l.Rb(a,this.I.getVideoData().lengthSeconds)};
g.k.QR=function(){g.Qb(this.B)||uRa(this,this.B);this.C=!1};
g.k.uJ=function(a,b){this.u.stop();2===b&&this.vK()};
g.k.au=function(){if(n9(this)){this.i.stop();var a=F8(this.Pb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.Ze=1;break;case 1082:case 1083:this.l.Ze=0;break;default:this.l.Ze=-1}switch(a.playerState){case 1081:case 1:this.Lb(new g.zK(8));this.uK();break;case 1085:case 3:this.Lb(new g.zK(9));break;case 1083:case 0:this.Lb(new g.zK(2));this.J.stop();this.Rb(this.I.getVideoData().lengthSeconds);break;case 1084:this.Lb(new g.zK(4));break;case 2:this.Lb(new g.zK(4));this.Rb(A8(a));
break;case -1:this.Lb(new g.zK(64));break;case -1E3:this.Lb(new g.zK(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=F8(this.Pb).trackData;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,uRa(this,a));a=F8(this.Pb);-1===a.volume||Math.round(this.I.getVolume())===a.volume&&this.I.isMuted()===a.muted||this.U.isActive()||this.bL()}else tRa(this)};
g.k.rJ=function(){this.I.W("mdxpreviousnextchange")};
g.k.Hx=function(){n9(this)||tRa(this)};
g.k.lJ=function(a){isNaN(a)||this.I.W("mdxnowautoplaying",a)};
g.k.LI=function(){this.I.W("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){n9(this)&&this.Pb.setAudioTrack(this.I.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===F8(this.Pb).playerState?p9(this,a):b&&this.Pb.seekTo(a)};
g.k.bL=function(){var a=this;if(n9(this)){var b=F8(this.Pb);this.events.fc(this.Y);b.muted?this.I.mute():this.I.unMute();this.I.setVolume(b.volume);this.Y=this.events.N(this.I,"onVolumeChange",function(c){sRa(a,c)})}};
g.k.uK=function(){this.i.stop();if(!this.Pb.Ha()){var a=F8(this.Pb);a.tc()&&this.Lb(new g.zK(8));this.Rb(A8(a));this.i.start()}};
g.k.vK=function(){this.u.stop();this.i.stop();var a=this.Pb.u.getReconnectTimeout();2==this.Pb.Oa&&!isNaN(a)&&this.u.start()};
g.k.Lb=function(a){this.u.stop();var b=this.G;if(!g.EK(b,a)){var c=g.U(a,2);c!==g.U(this.G,2)&&this.I.vp(c);this.G=a;wRa(this.l,b,a)}};g.v(q9,g.V);q9.prototype.Vc=function(){this.i.show()};
q9.prototype.Ab=function(){this.i.hide()};
q9.prototype.l=function(){g.gK("https://support.google.com/youtube/answer/7640706")};
q9.prototype.u=function(){G6("mdx-manual-pairing-popup-ok");this.Ab()};g.v(r9,g.V);r9.prototype.Vc=function(){this.i.show()};
r9.prototype.Ab=function(){this.i.hide()};
r9.prototype.l=function(){G6("mdx-privacy-popup-cancel");this.Ab()};
r9.prototype.u=function(){G6("mdx-privacy-popup-confirm");this.Ab()};g.v(s9,g.V);s9.prototype.l=function(a){vRa(this,a.state)};g.v(t9,g.pQ);t9.prototype.C=function(){var a=this.I.getOption("remote","receivers");a&&1<a.length&&!this.I.getOption("remote","quickCast")?(this.dn=g.Cb(a,this.i,this),g.qQ(this,g.Oe(a,this.i)),a=this.I.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.Gh(a),this.enable(!0)):this.enable(!1)};
t9.prototype.i=function(a){return a.key};
t9.prototype.Mi=function(a){return"cast-selector-receiver"===a?"Cast...":this.dn[a].name};
t9.prototype.kf=function(a){g.pQ.prototype.kf.call(this,a);this.I.setOption("remote","currentReceiver",this.dn[a]);this.xb.Ab()};g.v(u9,g.yN);g.k=u9.prototype;
g.k.create=function(){var a=this.player.T(),b=g.QF(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.S(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.S(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.S(a.experiments,"enable_cast_short_lived_lounge_token")};nRa(b,a);this.subscriptions.push(g.tu("yt-remote-before-disconnect",this.WQ,this));this.subscriptions.push(g.tu("yt-remote-connection-change",this.HS,this));this.subscriptions.push(g.tu("yt-remote-receiver-availability-change",
this.tJ,this));this.subscriptions.push(g.tu("yt-remote-auto-connect",this.ES,this));this.subscriptions.push(g.tu("yt-remote-receiver-resumed",this.DS,this));this.subscriptions.push(g.tu("mdx-privacy-popup-confirm",this.UT,this));this.subscriptions.push(g.tu("mdx-privacy-popup-cancel",this.TT,this));this.subscriptions.push(g.tu("mdx-manual-pairing-popup-ok",this.cQ,this));this.tJ()};
g.k.load=function(){this.player.cancelPlayback();g.yN.prototype.load.call(this);this.Jh=new m9(this,this.player,this.Pb);var a=(a=rRa())?a.currentTime:0;var b=j9()?new E8(d9(),void 0):null;0==a&&b&&(a=A8(F8(b)));0!==a&&this.Rb(a);wRa(this,this.hd,this.hd);this.player.vk(6)};
g.k.unload=function(){this.player.W("mdxautoplaycanceled");this.im=this.Yi;g.ef(this.Jh,this.Pb);this.Pb=this.Jh=null;g.yN.prototype.unload.call(this);this.player.vk(5);v9(this)};
g.k.ra=function(){g.uu(this.subscriptions);g.yN.prototype.ra.call(this)};
g.k.ek=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.Jh.Ui.apply(this.Jh,[a].concat(g.ma(c)))};
g.k.getAdState=function(){return this.Ze};
g.k.YO=function(){return this.loaded?this.Jh.suggestion:null};
g.k.Uj=function(){return this.Pb?F8(this.Pb).Uj:!1};
g.k.hasNext=function(){return this.Pb?F8(this.Pb).hasNext:!1};
g.k.Rb=function(a,b){this.fI=a||0;this.player.W("progresssync",a,b);this.player.Na("onVideoProgress",a)};
g.k.getCurrentTime=function(){return this.fI};
g.k.getProgressState=function(){var a=F8(this.Pb),b=this.player.getVideoData();return{allowSeeking:g.S(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Xe():!a.isAdPlaying()&&this.player.Xe(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.l?a.u+y8(a):a.u,isAtLiveHead:1>=(a.l?a.i+y8(a):a.i)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.l?a.i+y8(a):a.i,seekableStart:0<a.B?a.B+
y8(a):a.B}};
g.k.nextVideo=function(){this.Pb&&this.Pb.nextVideo()};
g.k.Mx=function(){this.Pb&&this.Pb.Mx()};
g.k.WQ=function(a){1===a&&(this.HC=this.Pb?F8(this.Pb):null)};
g.k.HS=function(){var a=j9()?new E8(d9(),void 0):null;if(a){var b=this.im;this.loaded&&this.unload();this.Pb=a;this.HC=null;b.key!==this.Yi.key&&(this.im=b,this.load())}else g.df(this.Pb),this.Pb=null,this.loaded&&(this.unload(),(a=this.HC)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,A8(a)));this.player.W("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.tJ=function(){var a=[this.Yi],b=a.concat,c=oRa();s8()&&g.jy("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.dn=b.call(a,c);a=e9()||this.Yi;w9(this,a);this.player.Na("onMdxReceiversChange")};
g.k.ES=function(){var a=e9();w9(this,a)};
g.k.DS=function(){this.im=e9()};
g.k.UT=function(){this.nu=!0;v9(this);l9=!1;f9&&h9(f9,1);f9=null};
g.k.TT=function(){this.nu=!1;v9(this);w9(this,this.Yi);this.im=this.Yi;l9=!1;f9=null;this.player.playVideo()};
g.k.cQ=function(){this.fx=!0;v9(this);g.iy("yt-remote-manual-pairing-warning-shown",!0,2592E3);l9=!1;f9&&h9(f9,1);f9=null};
g.k.Se=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.dn;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?u8():w9(this,b)),this.loaded?this.im:this.Yi;case "quickCast":return 2===this.dn.length&&"cast-selector-receiver"===this.dn[1].key?(b&&u8(),!0):!1}};
g.k.BD=function(){this.Pb.BD()};
g.k.wi=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.JN.remote=u9;})(_yt_player);
